### ISSUE TITLE
Suggestion: Add usage examples

### ISSUE THREAD

**Issue by hamiltonp** [lynxlynx/tfcrypt_public#1] opened 2017-08-30 21:33 UTC
I think I just found my perfect encryption tool because of 1024 bits cipher and dd command line style, but I'm having trouble to use, I don't know if it is a bug or incorrect usage, I can't encrypt anything using tfcrypt.

I want to encrypt files using threefish 1024 bits, max hash size, but all that I get is a chunk file with the same size as original which I can't decrypt later.

If you can include some example usages, mainly encrypt/decrypt files, I'd pleased.

**Comment by lynxlynx** [comment] 2017-09-05 07:40
(The process of writing a mdoc style manual page for the tool is in progress, but I simply cannot finish it in time. It will include an exhaustive list of examples of my own everyday use)

You should apply tfcrypt again back on encrypted stream. It will yield original, decrypted stream (of course if a key is valid). Example:
`tfcrypt /etc/passwd /bin/busybox | tfcrypt -d /etc/passwd | sk224sum - /bin/busybox`
should give same hashes. The first one encrypts, the second decrypts, and sk224sum verifies.

**Comment by hamiltonp** [comment] 2017-09-05 18:20
Thank you.

**Comment by lynxlynx** [comment] 2017-10-11 08:02
I found some time between other tasks to write the documentation and provide some examples. Please see the committed tfcrypt.1 manual page in the source tree or it's rendered ASCII version tfcrypt.1.txt to be viewed with `less tfcrypt.1.txt`. The list of examples in it is incomplete, but already extensive enough to give the first picture. I will collect some more interesting ones during everyday use. Upcoming are `sksum` examples as well.

Hope the issue is resolved. Have fun!

**Closed by lynxlynx** 2017-10-11 08:02 UTC
